### ISSUE TITLE
Question about approach-sensitive bitmap

### ISSUE THREAD

**Issue by 5hadowblad3** [rahlk/MTFuzz#2]
Hi, there.

I am a little confused about the approaches mentioned in the paper. 

According to the paper,
<img width="517" alt="image" src="https://user-images.githubusercontent.com/7632714/102784720-bd6d0400-43d7-11eb-82d9-86d6a0b692db.png">
<img width="657" alt="image" src="https://user-images.githubusercontent.com/7632714/102785874-9a435400-43d9-11eb-9cd4-91bdd98cb2a6.png">

the value of Belta should be 0.5.
However, I find that [this](https://github.com/rahlk/MTFuzz/blob/5ba5ee8260109d6d62d0e93e27d7fd0330cded2d/approach_pass/llvm_mode/afl-llvm-pass.so.cc#L285) number is set to be 1 instead, which means you count such edge as covered.

I do not find the place where you modify this value to 0.5.
Am I missing something or there is another explanation/handling for this value?

**Comment by Dongdongshe** [comment]
Hi,

Sorry for the confusion. There is an error in this graph. We were in a rush when submitting this paper. Please check the following graph which illustrates our approach level design.
![image](https://user-images.githubusercontent.com/9389471/112731353-12f00a00-8f0d-11eb-87b9-ea226b7f76b9.png)

Please let me know if you have any question about MTFuzz. I am happy to help.

Thank you,
Dongdong
