### ISSUE TITLE
./configure: No such file or directory

### ISSUE THREAD

**Issue by SAMIA-CLOUD** [rahlk/MTFuzz#3]
am trying to replicate this research https://github.com/rahlk/MTFuzz.
I have installed MTfuzz folder
whenever I tried to run
CC=ec_pass/afl-clang-fast ./configure && make # build ec coverage program

I get an error which is ./configure: No such file or directory

Please help

**Comment by SAMIA-CLOUD** [comment]
any help

**Comment by rahlk** [comment]
Let me get back to you this weekend with an updated readme. Thanks for you patience.

**Comment by SAMIA-CLOUD** [comment]
Please help

**Comment by rahlk** [comment]
Hi, where are you running ./configure from? This has to run from within your program source code. 

E.g., when get binutils source (from https://ftp.gnu.org/gnu/binutils/binutils-2.32.tar.gz) you would unzip it, cd into the unzipped folder, and then run `CC=<full_path_to_github_root_folder>/ec_pass/afl-clang-fast ./configure && make`

For your convenience, we have already compiled the binaries with each of these. See the programs folder. For eg, readily (https://github.com/rahlk/MTFuzz/tree/master/programs/readelf) has several binaries with readelf_ec, readelf_ctx, etc.
