### ISSUE TITLE
Exception of model training in benchmark mutool, hb-fuzzer and miniunz

### ISSUE THREAD

**Issue by leviljiang** [rahlk/MTFuzz#4]
## Description of exception

I try to reproduce the results of MTFuzz, but three benchmarks (mutool & hb-fuzzer & miniunz) fail due to the error below.

```
Traceback (most recent call last):
  File "nn.py", line 535, in <module>
    setup_server()
  File "nn.py", line 508, in setup_server
    gen_grad('train')
  File "nn.py", line 494, in gen_grad
    gen_mutate3(model,750, True, seed, label, weighted)
  File "nn.py", line 406, in gen_mutate3
    tmp_rand = np.random.choice(one_idx,1, replace=False)[0]
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```

Based on the exception I find that the training process of mt-nn model seems to be abnormal, where the loss is `nan` and accuracy is `0.0000e+00`. Then I check the loss function, the error may be caused by  the variable `pos_weight`. To be specific, `(np.sum(data==1, axis=0)+0.75*np.sum(data==0.25, axis=0))` contains elements with a value of zero and causes division by zero. 

```
Epoch 1/100
50/50 [==============================] - 3s 69ms/step - loss: nan - accur_1: 0.0000e+00
0.001
Epoch 2/100
50/50 [==============================] - 1s 30ms/step - loss: nan - accur_1: 0.0000e+00
0.001
Epoch 3/100
50/50 [==============================] - 1s 30ms/step - loss: nan - accur_1: 0.0000e+00
0.001
```

```python
opt = keras.optimizers.adam(lr=0.0001)
pos_weight = (np.sum(data==0, axis=0)+ np.sum(data==0.25, axis=0)/4) / (np.sum(data==1, axis=0)+0.75*np.sum(data==0.25, axis=0))
```

## Steps to reproduce

> Python 3.7 Tensorflow 1.15.0 Keras 2.2.4

- Take files in `MTFuzz/programs/mutool/mtfuzz_in` as the initial training seeds

- Start neural network module: `python nn.py ./mutool show`

- Start mtfuzz module: `python ./mtfuzz_wrapper.py -i mtfuzz_in -o seeds -l 4842 ./mutool show @@`

- At the end of the first training process, this exception occurs

**Comment by rahlk** [comment]
Hi, thanks for highlighting this issue. I will try to reproduce the error and get back to you.

**Comment by Dongdongshe** [comment]
Hi, 

This could be the same issue as you encountered in xmllint. In your environment, you might missing some dependency library to run the tested binary mupdf, harfbuzz and miniunz. Due to the failure of running these binaries, all edge label are empty and results in the error. 

Fix: run $ ldd ./mutool [./harfbuzz, ./miniunz] # find out all missing dependence library and install them.
