### ISSUE TITLE
Unable to communicate with fork server in xmllint

### ISSUE THREAD

**Issue by leviljiang** [rahlk/MTFuzz#5]
## Description

The benchmark xmllint fails when executing `mtfuzz_wrapper.py`. Part of the log shown below indicates that it is the error of fork server. Then the neural network module terminates with `IndexError`.

```
Fork server handshake failed: No such file or directory
...
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
...
```

```
Traceback (most recent call last):
  File "nn.py", line 535, in <module>
    setup_server()
  File "nn.py", line 508, in setup_server
    gen_grad('train')
  File "nn.py", line 490, in gen_grad
    seed, label = process_data()
  File "nn.py", line 264, in process_data
    print(fit_bitmap[:, np.asarray(reconstruct_idx)].shape, ec_num, ctx_num, soft_num)
IndexError: arrays used as indices must be of integer (or boolean) type
```

## Steps to reproduce

> Python 3.7 Tensorflow 1.15.0 Keras 2.2.4

- Take files in MTFuzz/programs/xmllint/mtfuzz_in as training seeds

- Start neural network module: python nn.py ./xmllint

- Start MTFuzz module: `python ./mtfuzz_wrapper.py -i mtfuzz_in -o seeds -l 8040 ./xmllint @@`

- The exception occurs when executing `mtfuzz_wrapper.py`

**Comment by rahlk** [comment]
Hi, thanks for highlighting this issue. I will try to reproduce the error and get back to you.

**Comment by SAMIA-CLOUD** [comment]
Hi

please can you help me in configuration

**Comment by Dongdongshe** [comment]
Hi,

I re-run the MTFuzz code for XML. It runs normally in my environment. The bug you encountered could be caused by missing independence library of the xmllint binary. So afl-showmap would fail to get any edge coverage and further result in a empty array at line 264 of nn.py.

Fix: run $ ldd ./xmllint  # find the missing library on your environment, then install the missing library.

Please let me know if works for you. I am happy to help.

Thank you,
Dongdong
