### ISSUE TITLE
Exception of FileNotFoundError when executing objdump

### ISSUE THREAD

**Issue by leviljiang** [rahlk/MTFuzz#6]
## Description of exception

Hi~ When I try to execute the benchmark of `objdump`, the mtfuzz_wrapper.py terminates with the exception below.

~~~
Traceback (most recent call last):
  File "./mtfuzz_wrapper.py", line 369, in crack
    out = check_out(['./afl-showbr', '-q', '-o', '/dev/stdout', '-m', '1024', '-t', '5000'] + tmp_argvv[6:-1] + [seed])
  File "/home/cseadmin/anaconda3/envs/mtfuzz_env/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/cseadmin/anaconda3/envs/mtfuzz_env/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./afl-showbr', '-q', '-o', '/dev/stdout', '-m', '1024', '-t', '5000', './objdump_br', '-D', './tmp_input']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./mtfuzz_wrapper.py", line 1458, in <module>
    main()
  File "./mtfuzz_wrapper.py", line 1455, in main
    crack(tmp_argvv, argvv)
  File "./mtfuzz_wrapper.py", line 371, in crack
    print("### found a crash " + str(k) + " br_tyte "+ br_type)
TypeError: can only concatenate str (not "int") to str
~~~

I think it is a bug when a crash seed file is handled, I try to fix the bug because I think it is caused for the reason that  `br_type` is not transformed to `str`. I change the code `br_type` to `str(br_type)`, but another `FileNotFoundError` occurs. And I fail to reproduce the data claimed in paper.

Could you fix the bug? And I am quite confused about the function `crack()` where the exception occurs, could you explain the function in detail？

## Steps to reproduce

> Python 3.7 Tensorflow 1.15.0 Keras 2.2.4

- Take files in MTFuzz/programs/objdump/mtfuzz_in as the initial training seeds

- Start nn module with `python nn.py ./objdump -D`

- Start MTFuzz module with `python ./mtfuzz_wrapper.py -i mtfuzz_in -o seeds -l 7376 ./objdump -D @@`

- When handling the crash file in function `crack()`, the exception occurs.

**Comment by Dongdongshe** [comment]
Hi,

The crash log seems only about wrong concatenation of number and string. Could you show more detailed about FileNotFoundError? I am guessing it could be wrong directory to run the code. One quick check is that to ensure you are running this program under programs/objdump.

The crack() functions simply crack some hard constraints such as magic checking (e.g., if (a == 0xdeadbeef) ).

Thank you,
Dongdong

**Comment by SAMIA-CLOUD** [comment]
Dear  Dongdongshe

May I get your personal email. I have to optimize this project but I still get these errors. I don`t know how I send you a screenshot here.

Please here is my personal email sma225@njit.edu.

**Comment by leviljiang** [comment]
Hi Dongdong,

I still wonder about the function of `crack()`, if I wanna extend other programs. The exception of no `program_br_log` file occurs. I didn't find any programs that could generate the `br_log` file based on other programs. So could you give me some guidance. Also, is the crack part mentioned in the MTFuzz paper? 

Thx very much

**Comment by Dongdongshe** [comment]
> Hi Dongdong,
> 
> I still wonder about the function of `crack()`, if I wanna extend other programs. The exception of no `program_br_log` file occurs. I didn't find any programs that could generate the `br_log` file based on other programs. So could you give me some guidance. Also, is the crack part mentioned in the MTFuzz paper?
> 
> Thx very much

Hi, 

We actually have a tutorial on how to run MTFuzz on other programs. It somehow missing in this repo. Please check https://github.com/Dongdongshe/fse20/tree/a873e86bfa2e3219bba1b16287353bce85373b8d/submissions/reusable/mtfuzz/source/programs. You will find a bash script setup_mtfuzz_xmlwf.sh to show how to run MTFuzz on another program xmlwf. I also merged those tutorial in this repo. You can directly access them now at programs/Readme.md

This crack() module in mentioned in our paper section 4, https://dl.acm.org/doi/pdf/10.1145/3368089.3409723.

Please let me know if you have other to run MTFuzz.

Best,
Dongdong

**Comment by Dongdongshe** [comment]
> Dear Dongdongshe
> 
> May I get your personal email. I have to optimize this project but I still get these errors. I don`t know how I send you a screenshot here.
> 
> Please here is my personal email [sma225@njit.edu](mailto:sma225@njit.edu).

dongdong@cs.columbia.edu
