### ISSUE TITLE
Can you help to solve this problem

### ISSUE THREAD

**Issue by SAMIA-CLOUD** [rahlk/MTFuzz#8]
ValueError: cannot reshape array of size 0 into shape (0,newaxis)
err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe
err0: Unable to communicate with fork server (OOM?)err-1: Unable to request new process from fork server (OOM?)err0: Unable to request new process from fork server (OOM?)Fork server is misbehaving (OOM?): Broken pipe

### found a crash 
1593 0 0
Traceback (most recent call last):
  File "./mtfuzz_wrapper.py", line 1454, in <module>
    main()
  File "./mtfuzz_wrapper.py", line 1451, in main
    crack(tmp_argvv, argvv)
  File "./mtfuzz_wrapper.py", line 199, in crack
    del unexplored[0]
KeyError: 0
login-1-49 readelf >:

**Comment by Dongdongshe** [comment]
Hi,

It seems you have some configuration or setup issue on MTFuzz. You can send me email(dongdong at cs.columbia.edu) about more details. I am happy to help. 

Best,
Dongdong
